### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by laozheng1** [AriSaadon/RoadMapConstructionEvaluation#2]
Hi! Air.
Why doesn't the scene show up when I run it?  Could you tell me what went wrong?  
I would be most grateful if you could give me any help.  
![b07831b0239ba18d58195626aaa3211](https://user-images.githubusercontent.com/70837331/159619715-5e427f9d-bc22-457a-ade9-675cc60cc220.png)

**Comment by AriSaadon** [comment]
Hi Laozheng, I just tried to open the project up in a new unity project using Unity 2019.4.2f1 personal edition.
I opened the unity hub and added the evaluator folder as a new project.
When added I had the following window.
![image](https://user-images.githubusercontent.com/9694781/159696647-72c32656-b2aa-4182-97d9-4f2741e47a32.png)
Please check if all the highlighted parts are correct and correspond to your editor.
On hitting play, the maps were correctly imported and I could view a scene.
So on my end everything seems to be working.
Hope this helps, but otherwise please tell me.

**Comment by laozheng1** [comment]
Thank you for your reply! Your answer is very helpful to me!
I have another question. 

This is my run result.
![7T7`SH)4Y$6BGA71 1LPYHC](https://user-images.githubusercontent.com/70837331/159740832-37a84e56-ab80-4442-9442-11bcc2779a74.png)

How can I get results like yours?
![U@~CC~7CNVE`M8EYXZSWA8X](https://user-images.githubusercontent.com/70837331/159741066-7f97a362-c9b6-4c68-8fcc-a5fa8978731c.jpg)

I would be most grateful if you could give me any help.

**Comment by AriSaadon** [comment]
This is not really an issue related to the framework that I provide. But to elaborate on the particular result that you want to create:
The custom view that my result shows is not a direct feature. 
The evaluator allows you to make images like that.
But to do so you should utilize unity features to position both the trajectories and the maps side by side. 
you can position a certain object _obj_ in unity with: _obj.transform.position = new vector3(x,y,z)_.
Depending on the size the trajectories and map take in, you might have to trial-and-error to find the exact coordinates.

Hope this somewhat helps, but again, this is not an issue with the evaluator, its more about utilizing unity features. I will thus close this issue. Best of luck!
